CREATE TABLE `book` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOOK_TITLE` varchar(255) NOT NULL,
  `BOOK_AUTHOR` varchar(255) NOT NULL,
  `BOOK_PRICE` int(11) NOT NULL,
  `BOOK_IMG` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8