INSERT INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE , BOOK_IMG) VALUES ('1', 'First Book', 'First Author', '30000', 1.jpg);
INSERT INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE , BOOK_IMG) VALUES ('2', 'Second Book', 'Second Author', '20000', 2.jpg);
INSERT INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE , BOOK_IMG) VALUES ('3', 'Third Book', 'Third Author', '15000', 3.jpg);
INSERT INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE , BOOK_IMG) VALUES ('4', 'Fourth Book', 'Fourth Author', '25000', 4.jpg);
INSERT INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE , BOOK_IMG) VALUES ('5', 'Fifth Book', 'Fifth Author', '80000', 5.jpg);
INSERT INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE , BOOK_IMG) VALUES ('6', 'Sixth Book', 'Sixth Author', '50000', 6.png);
